version: '3.8'
services:
  
  site:
    build:
      context: .
      dockerfile: docker-site/Dockerfile
    ports:
      - "8001:80"
    volumes:
      - ./site_libraries:/var/www/html
      - ./nginx/nginx-site.conf:/etc/nginx/sites-enabled/myapp.conf
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    container_name: phpmyadmin
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  db_data:
